name = "Modpack"
author = "AlexGlitch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "503358941d4b76b0adc29d80d526809b265404f36e9efb9113c3a317c1065a3e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.194"
