name = "Modpack"
author = "AlexGlitch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88c6a4278247197b4168a83c4f4066bf6dcd8b5ad1ad3707436011b1bac77cc3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.194"
