name = "Modpack"
author = "AlexGlitch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9de1881c44afcb713646897259cf9519560a37df5c9a5b4c1be4d86c48c7ebcb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.194"
