name = "Modpack"
author = "AlexGlitch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b50d63760711751cf4ce8d0f500af05bee9f8bc0dfcd0d61029af88c862b71bf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.194"
