name = "Modpack"
author = "AlexGlitch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f57b33f1010239cf73757b1bb273e3a60153fe9e860bbdebb94f882585847df"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.194"
