name = "Modpack"
author = "AlexGlitch"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3c678a45f0595a77b1b9166c20d8fbd374e6005803ad5bbd0cba4ead8da170d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.194"
